import type { CandidateProvider,ExperimentMode,GraphProvider,JudgeResult,JevJudge,Judgment,Limits,Memory,RetrievalResult,Trace } from "./types";
export const DEFAULT_LIMITS:Limits={initialCandidates:8,maxCandidates:20,maxHops:2,maxGraphReads:20,maxTypeSafeRequests:4,maxInputTokens:12000,contextTokens:700,timeoutMs:8000,retries:2};
const tokens=(s:string)=>Math.ceil(s.length/4);
const current=(m:Memory,tenant:string,now:string)=>m.tenantId===tenant&&(!m.expiresAt||m.expiresAt>now)&&!m.supersededBy;
export const baselineRank=(xs:Memory[])=>[...xs].sort((a,b)=>b.initialScore-a.initialScore||a.id.localeCompare(b.id));
export const baselineExpand=(edges:{to:string}[])=>[...edges].sort((a,b)=>a.to.localeCompare(b.to));
function unique(xs:Memory[]){const seen=new Set<string>();return xs.filter(x=>!seen.has(x.id)&&!!seen.add(x.id));}
function valid(result:JudgeResult,allowed:Set<string>):Judgment[]{if(!result||!Array.isArray(result.judgments))throw new Error("malformed judgment");return result.judgments.map(j=>{if(!allowed.has(j.id)||!Number.isFinite(j.score)||j.score<0||j.score>1||typeof j.rationale!=="string")throw new Error("malformed judgment");return j;});}
async function call(judge:JevJudge,input:Parameters<JevJudge["judge"]>[0],limits:Limits,trace:Trace){let last:unknown;for(let n=0;n<=limits.retries;n++){if(trace.typeSafeRequests>=limits.maxTypeSafeRequests)throw new Error("TypeSafe request limit");trace.typeSafeRequests++;const ctl=new AbortController();const timer=setTimeout(()=>ctl.abort(),limits.timeoutMs);try{return await judge.judge({...input,signal:ctl.signal});}catch(e){last=e;}finally{clearTimeout(timer);}}throw last;}
function select(xs:Memory[],budget:number){const out:Memory[]=[];let used=0;for(const x of xs){const n=tokens(x.text);if(used+n>budget)continue;out.push(x);used+=n;}return out;}
export async function retrieve(args:{mode:ExperimentMode;query:string;tenantId:string;candidateProvider:CandidateProvider;graphProvider:GraphProvider;judge?:JevJudge;limits?:Partial<Limits>;now?:string}):Promise<RetrievalResult>{
 const started=performance.now(),limits={...DEFAULT_LIMITS,...args.limits};const trace:Trace={graphReads:0,candidateCount:0,typeSafeRequests:0,usage:{},fallback:false,fallbackReasons:[],latencyMs:0};const now=args.now??new Date().toISOString();let all=unique((await args.candidateProvider.candidates(args.query,args.tenantId,limits.initialCandidates)).filter(m=>current(m,args.tenantId,now))).slice(0,limits.maxCandidates);
 const jevExpand=args.mode==="graph-traversal-only"||args.mode==="reranker-and-traversal";let frontier=[...all];const visited=new Set(all.map(x=>x.id));
 for(let hop=0;hop<limits.maxHops&&frontier.length&&all.length<limits.maxCandidates;hop++){const choices:{from:Memory;targets:Memory[]}[]=[];for(const source of frontier){if(trace.graphReads>=limits.maxGraphReads)break;trace.graphReads++;const edges=baselineExpand(await args.graphProvider.neighbors(source.id,args.tenantId));const ids=edges.map(e=>e.to).filter(id=>!visited.has(id));if(!ids.length)continue;const targets=unique((await args.graphProvider.get(ids,args.tenantId)).filter(m=>current(m,args.tenantId,now)));choices.push({from:source,targets});}
 let next=unique(choices.flatMap(x=>x.targets));if(jevExpand&&next.length&&args.judge){try{const result=await call(args.judge,{purpose:"expand",query:args.query,candidates:next,criteria:"Expand only targets likely to provide evidence needed to answer the query; score 0..1.",signal:new AbortController().signal},limits,trace);const js=valid(result,new Set(next.map(x=>x.id)));trace.usage={inputTokens:(trace.usage.inputTokens??0)+(result.usage?.inputTokens??0),outputTokens:(trace.usage.outputTokens??0)+(result.usage?.outputTokens??0),costUsd:(trace.usage.costUsd??0)+(result.usage?.costUsd??0)};const keep=new Set(js.filter(j=>j.expand??j.score>=.5).map(j=>j.id));next=next.filter(x=>keep.has(x.id));}catch(e){trace.fallback=true;trace.fallbackReasons.push(`expand: ${e instanceof Error?e.message:String(e)}`);}}
 next=next.slice(0,limits.maxCandidates-all.length);for(const x of next)visited.add(x.id);all.push(...next);frontier=next;}
 trace.candidateCount=all.length;let ranked=baselineRank(all);const jevRank=args.mode==="reranker-only"||args.mode==="reranker-and-traversal";if(jevRank&&all.length&&args.judge){try{const result=await call(args.judge,{purpose:"rank",query:args.query,candidates:all,criteria:"Score answer-bearing relevance 0..1; prefer current evidence and historical evidence only for historical queries.",signal:new AbortController().signal},limits,trace);const js=valid(result,new Set(all.map(x=>x.id))),scores=new Map(js.map(j=>[j.id,j.score]));ranked=[...all].sort((a,b)=>(scores.get(b.id)??-1)-(scores.get(a.id)??-1)||b.initialScore-a.initialScore||a.id.localeCompare(b.id));trace.usage={inputTokens:(trace.usage.inputTokens??0)+(result.usage?.inputTokens??0),outputTokens:(trace.usage.outputTokens??0)+(result.usage?.outputTokens??0),costUsd:(trace.usage.costUsd??0)+(result.usage?.costUsd??0)};}catch(e){trace.fallback=true;trace.fallbackReasons.push(`rank: ${e instanceof Error?e.message:String(e)}`);}}
 const memories=select(ranked,limits.contextTokens);trace.latencyMs=performance.now()-started;return{memories,context:memories.map(m=>`[${m.id}; document=${m.source.documentId}; chunk=${m.source.chunkId}]\n${m.text}`).join("\n\n"),trace};}
