import {describe,expect,test} from "bun:test";import {retrieve} from "../src/core";import {FixtureProvider} from "../src/providers";import type {Edge,JevJudge,Memory} from "../src/types";
const m=(id:string,score:number,extra:Partial<Memory>={}):Memory=>({id,tenantId:"a",text:`evidence ${id}`,source:{documentId:`d-${id}`,chunkId:`c-${id}`},createdAt:"2025-01-01T00:00:00Z",initialScore:score,...extra});
const run=(mode:any,memories:Memory[],edges:Edge[]=[],judge?:JevJudge,limits={})=>{const p=new FixtureProvider(memories,edges);return retrieve({mode,query:"q",tenantId:"a",candidateProvider:p,graphProvider:p,judge,limits,now:"2026-01-01T00:00:00Z"})};
const judge=(fn:(purpose:string,ids:string[])=>any):JevJudge=>({judge:async x=>fn(x.purpose,x.candidates.map(c=>c.id))});
describe("prototype ablations",()=>{
 test("empty candidates",async()=>expect((await run("baseline",[])).memories).toEqual([]));
 test("deduplicates and isolates tenant",async()=>{const x=m("x",1),other=m("z",1,{tenantId:"b"});expect((await run("baseline",[x,x,other])).memories.map(x=>x.id)).toEqual(["x"])});
 test("removes expired and known superseded facts",async()=>{expect((await run("baseline",[m("old",1,{supersededBy:"new"}),m("expired",.9,{expiresAt:"2025-01-01T00:00:00Z"}),m("new",.1)])).memories.map(x=>x.id)).toEqual(["new"])});
 test("Jev ranking is deterministic and preserves provenance",async()=>{const j=judge((_p,ids)=>({judgments:ids.map(id=>({id,score:.8,rationale:"observed candidate relevant"}))}));const r=await run("reranker-only",[m("b",.5),m("a",.5)],[],j);expect(r.memories.map(x=>x.id)).toEqual(["a","b"]);expect(r.context).toContain("document=d-a; chunk=c-a")});
 test("bounded multi-hop handles missing targets and cycles",async()=>{const xs=[m("a",1),m("b",.1),m("c",.05)];const edges=[{from:"a",to:"b",relation:"r"},{from:"a",to:"missing",relation:"r"},{from:"b",to:"c",relation:"r"},{from:"c",to:"a",relation:"cycle"}];const r=await run("graph-traversal-only",xs,edges,judge((_p,ids)=>({judgments:ids.map(id=>({id,score:1,expand:true,rationale:"needed"}))})),{initialCandidates:1,maxHops:2});expect(r.memories.map(x=>x.id)).toEqual(["a","b","c"]);expect(r.trace.graphReads).toBe(2)});
 test("irrelevant frontier is not expanded",async()=>{const xs=[m("a",1),m("b",.1)];const r=await run("graph-traversal-only",xs,[{from:"a",to:"b",relation:"r"}],judge((_p,ids)=>({judgments:ids.map(id=>({id,score:0,expand:false,rationale:"irrelevant"}))})),{initialCandidates:1});expect(r.memories.map(x=>x.id)).toEqual(["a"])});
 test("malformed response and service failure record fallback",async()=>{let calls=0;const j: JevJudge={judge:async()=>{calls++;throw new Error("down")}};const r=await run("reranker-only",[m("b",.2),m("a",.2)],[],j,{retries:1});expect(r.trace.fallback).toBe(true);expect(r.trace.fallbackReasons[0]).toContain("down");expect(calls).toBe(2);expect(r.memories.map(x=>x.id)).toEqual(["a","b"])});
 test("context and request budgets are enforced",async()=>{const xs=[m("a",1,{text:"x".repeat(20)}),m("b",.9,{text:"y".repeat(20)})];const r=await run("reranker-only",xs,[],judge((_p,ids)=>({judgments:ids.map(id=>({id,score:1,rationale:"yes"}))})),{contextTokens:5,maxTypeSafeRequests:0});expect(r.memories).toHaveLength(1);expect(r.trace.typeSafeRequests).toBe(0);expect(r.trace.fallback).toBe(true)});
 test("combined mode batches each shared frontier and ranking",async()=>{const calls:string[]=[];const j=judge((p,ids)=>{calls.push(`${p}:${ids.join(",")}`);return{judgments:ids.map(id=>({id,score:id==="b"?1:.5,expand:true,rationale:"evidence"}))}});await run("reranker-and-traversal",[m("a",1),m("b",.1)],[{from:"a",to:"b",relation:"r"}],j,{initialCandidates:1,maxHops:1});expect(calls).toEqual(["expand:b","rank:a,b"])});
});
